check50:
  files: &check50_files
    - !exclude "*"
    - !require ciegos.py
  checks:
    muro_0:
      - run: python3 ciegos.py
        stdin:
          - V--V----V--P--VV---V------V--P--V--V
          - 5
        stdout:
          - 4
        exit: 0
    muro_1:
      - run: python3 ciegos.py
        stdin:
          - V--V----V--P--VV---V------V--P--V--V
          - 6
        stdout:
          - 1
        exit: 0
    muro_2:
      - run: python3 ciegos.py
        stdin:
          - V--V----V--P--VV---V------V--P--V--V
          - 7
        stdout:
          - 0
        exit: 0
    muro_3:
      - run: python3 ciegos.py
        stdin:
          - V--V----V--P--VV---V-----V--P--V--V
          - 5
        stdout:
          - 3
        exit: 0
    muro_4:
      - run: python3 ciegos.py
        stdin:
          - V--V--V
          - 2
        stdout:
          - 2
        exit: 0
    muro_5:
      - run: python3 ciegos.py
        stdin:
          - V--V--V--P-V
          - 2
        stdout:
          - 5
        exit: 0
    muro_6:
      - run: python3 ciegos.py
        stdin:
          - V-P-V-P-V
          - 3
        stdout:
          - 2
        exit: 0
    muro_7:
      - run: python3 ciegos.py
        stdin:
          - VP-VP-V--V--VPPV
          - 2
        stdout:
          - 5
        exit: 0
    muro_8:
      - run: python3 ciegos.py
        stdin:
          - VPPPVPPV--V--VPPV
          - 3
        stdout:
          - 1
        exit: 0
    muro_9:
      - run: python3 ciegos.py
        stdin:
          - VPPPVPPPV----V
          - 4
        stdout:
          - 1
        exit: 0
    muro_10:
      - run: python3 ciegos.py
        stdin:
          - VPPPP-V-----VP-P-PV
          - 5
        stdout:
          - 3
        exit: 0
    muro_11:
      - run: python3 ciegos.py
        stdin:
          - VPPPVPPPVPPPPV
          - 3
        stdout:
          - 4
        exit: 0
    muro_12:
      - run: python3 ciegos.py
        stdin:
          - VPP--VPP--V
          - 4
        stdout:
          - 2
        exit: 0
    muro_13:
      - run: python3 ciegos.py
        stdin:
          - VVV-P-VVPPPV--PV
          - 3
        stdout:
          - 3
        exit: 0
    muro_14:
      - run: python3 ciegos.py
        stdin:
          - VVVP-V-P-VV---VPPV
          - 3
        stdout:
          - 2
        exit: 0
    muro_15:
      - run: python3 ciegos.py
        stdin:
          - VVV--PPV-P-PVPP--V
          - 4
        stdout:
          - 3
        exit: 0
    muro_16:
      - run: python3 ciegos.py
        stdin:
          - VVV--PPV-P-PVPP--VPPPV----V--VPPV
          - 4
        stdout:
          - 4
        exit: 0
    muro_17:
      - run: python3 ciegos.py
        stdin:
          - VVV--PPV-P-PVPPV-VPPPV-V--V--VPPV
          - 5
        stdout:
          - 0
        exit: 0
    muro_18:
      - run: python3 ciegos.py
        stdin:
          - VVVP-V-P-VV----VPPV
          - 4
        stdout:
          - 1
        exit: 0
    muro_19:
      - run: python3 ciegos.py
        stdin:
          - VVVP-V-P-VV----VPPV
          - 5
        stdout:
          - 0
        exit: 0
    muro_20:
      - run: python3 ciegos.py
        stdin:
          - VVV--PPV-P-PVPP--V
          - 5
        stdout:
          - 0
        exit: 0
    muro_21:
      - run: python3 ciegos.py
        stdin:
          - VVV--VVPPPV--V
          - 3
        stdout:
          - 1
        exit: 0
    muro_22:
      - run: python3 ciegos.py
        stdin:
          - VVV--VVPPPV--PV
          - 3
        stdout:
          - 2
        exit: 0
    muro_23:
      - run: python3 ciegos.py
        stdin:
          - VVV-P-VVPPPV--PV
          - 3
        stdout:
          - 3
        exit: 0
    muro_24:
      - run: python3 ciegos.py
        stdin:
          - VVV-P-VVPPPV--PV
          - 4
        stdout:
          - 0
        exit: 0
    muro_25:
      - run: python3 ciegos.py
        stdin:
          - VVV-P-VVPP--PV--PV
          - 5
        stdout:
          - 1
        exit: 0
    muro_26:
      - run: python3 ciegos.py
        stdin:
          - VVV-P-VVPP--PV--PV
          - 6
        stdout:
          - 0
        exit: 0
    muro_27:
      - run: python3 ciegos.py
        stdin:
          - VVV-P-PVVPP--PV--PV
          - 4
        stdout:
          - 3
        exit: 0
    muro_28:
      - run: python3 ciegos.py
        stdin:
          - VVVPPPPP-V
          - 6
        stdout:
          - 1
        exit: 0
    muro_29:
      - run: python3 ciegos.py
        stdin:
          - VVVPPPPPP-V
          - 6
        stdout:
          - 2
submit50:
  files: *check50_files
