check50:
  checks:
    triangulo_1:
      - run: python3 hipotenusa.py
        stdin:
          - 3
          - 4
        stdout: "Hipotenusa: 5"
        exit: 0
    triangulo_2:
      - run: python3 hipotenusa.py
        stdin:
          - 6
          - 8
        stdout: "Hipotenusa: 10"
        exit: 0
    triangulo_3:
      - run: python3 hipotenusa.py
        stdin:
          - 5
          - 12
        stdout: "Hipotenusa: 13"
        exit: 0
    triangulo_4:
      - run: python3 hipotenusa.py
        stdin:
          - 120
          - 209
        stdout: "Hipotenusa: 241"
        exit: 0
    triangulo_5:
      - run: python3 hipotenusa.py
        stdin:
          - 32
          - 255
        stdout: "Hipotenusa: 257"
        exit: 0
    triangulo_6:
      - run: python3 hipotenusa.py
        stdin:
          - 160
          - 231
        stdout: "Hipotenusa: 281"
        exit: 0
    triangulo_7:
      - run: python3 hipotenusa.py
        stdin:
          - 68
          - 285
        stdout: "Hipotenusa: 293"
        exit: 0
    triangulo_8:
      - run: python3 hipotenusa.py
        stdin:
          - 115
          - 252
        stdout: "Hipotenusa: 277"
        exit: 0
submit50: true
