check50:
  files: &check50_files
    - !exclude "*"
    - !require numeros_introescos.py
  checks:
    numero_0:
      - run: python3 numeros_introescos.py
        stdin:
          - 1100
          - 1150
        stdout:
          - 1103
          - 1130
          - 2
        exit: 0
    numero_1:
      - run: python3 numeros_introescos.py
        stdin:
          - 1101
          - 1160
        stdout:
          - 1103
          - 1130
          - 2
        exit: 0
    numero_2:
      - run: python3 numeros_introescos.py
        stdin:
          - 1
          - 10
        stdout:
          - 0
        exit: 0
    numero_3:
      - run: python3 numeros_introescos.py
        stdin:
          - 999
          - 1000
        stdout:
          - 0
        exit: 0
    numero_4:
      - run: python3 numeros_introescos.py
        stdin:
          - 9000
          - 15000
        stdout:
          - 10013
          - 10031
          - 10103
          - 10113
          - 10123
          - 10130
          - 10131
          - 10132
          - 10133
          - 10134
          - 10135
          - 10136
          - 10137
          - 10138
          - 10139
          - 10143
          - 10153
          - 10163
          - 10173
          - 10183
          - 10193
          - 10213
          - 10231
          - 10301
          - 10310
          - 10311
          - 10312
          - 10313
          - 10314
          - 10315
          - 10316
          - 10317
          - 10318
          - 10319
          - 10321
          - 10331
          - 10341
          - 10351
          - 10361
          - 10371
          - 10381
          - 10391
          - 10413
          - 10431
          - 10513
          - 10531
          - 10613
          - 10631
          - 10713
          - 10731
          - 10813
          - 10831
          - 10913
          - 10931
          - 11003
          - 11013
          - 11023
          - 11030
          - 11031
          - 11032
          - 11033
          - 11034
          - 11035
          - 11036
          - 11037
          - 11038
          - 11039
          - 11043
          - 11053
          - 11063
          - 11073
          - 11083
          - 11093
          - 11103
          - 11130
          - 11203
          - 11230
          - 11300
          - 11301
          - 11302
          - 11303
          - 11304
          - 11305
          - 11306
          - 11307
          - 11308
          - 11309
          - 11310
          - 11320
          - 11330
          - 11340
          - 11350
          - 11360
          - 11370
          - 11380
          - 11390
          - 11403
          - 11430
          - 11503
          - 11530
          - 11603
          - 11630
          - 11703
          - 11730
          - 11803
          - 11830
          - 11903
          - 11930
          - 12013
          - 12031
          - 12103
          - 12130
          - 12301
          - 12310
          - 13001
          - 13010
          - 13011
          - 13012
          - 13013
          - 13014
          - 13015
          - 13016
          - 13017
          - 13018
          - 13019
          - 13021
          - 13031
          - 13041
          - 13051
          - 13061
          - 13071
          - 13081
          - 13091
          - 13100
          - 13101
          - 13102
          - 13103
          - 13104
          - 13105
          - 13106
          - 13107
          - 13108
          - 13109
          - 13110
          - 13120
          - 13130
          - 13140
          - 13150
          - 13160
          - 13170
          - 13180
          - 13190
          - 13201
          - 13210
          - 13301
          - 13310
          - 13401
          - 13410
          - 13501
          - 13510
          - 13601
          - 13610
          - 13701
          - 13710
          - 13801
          - 13810
          - 13901
          - 13910
          - 14013
          - 14031
          - 14103
          - 14130
          - 14301
          - 14310
          - 174
        exit: 0
    numero_5:
      - run: python3 numeros_introescos.py
        stdin:
          - 16000
          - 17000
        stdout:
          - 16013
          - 16031
          - 16103
          - 16130
          - 16301
          - 16310
          - 6
        exit: 0
    numero_6:
      - run: python3 numeros_introescos.py
        stdin:
          - 1103
          - 1104
        stdout:
          - 1103
          - 1
        exit: 0
    numero_7:
      - run: python3 numeros_introescos.py
        stdin:
          - 1100
          - 1103
        stdout:
          - 1103
          - 1
        exit: 0
    numero_8:
      - run: python3 numeros_introescos.py
        stdin:
          - 999
          - 1104
        stdout:
          - 1013
          - 1031
          - 1103
          - 3
        exit: 0
    numero_9:
      - run: python3 numeros_introescos.py
        stdin:
          - 3000
          - 3113
        stdout:
          - 3011
          - 3101
          - 3110
          - 3
        exit: 0
    numero_10:
      - run: python3 numeros_introescos.py
        stdin:
          - 1
          - 2000
        stdout:
          - 1013
          - 1031
          - 1103
          - 1130
          - 1301
          - 1310
          - 6
        exit: 0
    numero_11:
      - run: python3 numeros_introescos.py
        stdin:
          - 11111111
          - 11111200
        stdout:
          - 11111130
          - 1
        exit: 0
    numero_12:
      - run: python3 numeros_introescos.py
        stdin:
          - 333333333
          - 333333999
        stdout:
          - 0
        exit: 0
    numero_13:
      - run: python3 numeros_introescos.py
        stdin:
          - 2222222
          - 2225000
        stdout:
          - 2223011
          - 2223101
          - 2223110
          - 3
        exit: 0
    numero_14:
      - run: python3 numeros_introescos.py
        stdin:
          - 10000
          - 30000
        stdout:
          - 10013
          - 10031
          - 10103
          - 10113
          - 10123
          - 10130
          - 10131
          - 10132
          - 10133
          - 10134
          - 10135
          - 10136
          - 10137
          - 10138
          - 10139
          - 10143
          - 10153
          - 10163
          - 10173
          - 10183
          - 10193
          - 10213
          - 10231
          - 10301
          - 10310
          - 10311
          - 10312
          - 10313
          - 10314
          - 10315
          - 10316
          - 10317
          - 10318
          - 10319
          - 10321
          - 10331
          - 10341
          - 10351
          - 10361
          - 10371
          - 10381
          - 10391
          - 10413
          - 10431
          - 10513
          - 10531
          - 10613
          - 10631
          - 10713
          - 10731
          - 10813
          - 10831
          - 10913
          - 10931
          - 11003
          - 11013
          - 11023
          - 11030
          - 11031
          - 11032
          - 11033
          - 11034
          - 11035
          - 11036
          - 11037
          - 11038
          - 11039
          - 11043
          - 11053
          - 11063
          - 11073
          - 11083
          - 11093
          - 11103
          - 11130
          - 11203
          - 11230
          - 11300
          - 11301
          - 11302
          - 11303
          - 11304
          - 11305
          - 11306
          - 11307
          - 11308
          - 11309
          - 11310
          - 11320
          - 11330
          - 11340
          - 11350
          - 11360
          - 11370
          - 11380
          - 11390
          - 11403
          - 11430
          - 11503
          - 11530
          - 11603
          - 11630
          - 11703
          - 11730
          - 11803
          - 11830
          - 11903
          - 11930
          - 12013
          - 12031
          - 12103
          - 12130
          - 12301
          - 12310
          - 13001
          - 13010
          - 13011
          - 13012
          - 13013
          - 13014
          - 13015
          - 13016
          - 13017
          - 13018
          - 13019
          - 13021
          - 13031
          - 13041
          - 13051
          - 13061
          - 13071
          - 13081
          - 13091
          - 13100
          - 13101
          - 13102
          - 13103
          - 13104
          - 13105
          - 13106
          - 13107
          - 13108
          - 13109
          - 13110
          - 13120
          - 13130
          - 13140
          - 13150
          - 13160
          - 13170
          - 13180
          - 13190
          - 13201
          - 13210
          - 13301
          - 13310
          - 13401
          - 13410
          - 13501
          - 13510
          - 13601
          - 13610
          - 13701
          - 13710
          - 13801
          - 13810
          - 13901
          - 13910
          - 14013
          - 14031
          - 14103
          - 14130
          - 14301
          - 14310
          - 15013
          - 15031
          - 15103
          - 15130
          - 15301
          - 15310
          - 16013
          - 16031
          - 16103
          - 16130
          - 16301
          - 16310
          - 17013
          - 17031
          - 17103
          - 17130
          - 17301
          - 17310
          - 18013
          - 18031
          - 18103
          - 18130
          - 18301
          - 18310
          - 19013
          - 19031
          - 19103
          - 19130
          - 19301
          - 19310
          - 20113
          - 20131
          - 20311
          - 21013
          - 21031
          - 21103
          - 21130
          - 21301
          - 21310
          - 23011
          - 23101
          - 23110
          - 216
        exit: 0
    numero_15:
      - run: python3 numeros_introescos.py
        stdin:
          - 33110
          - 36110
        stdout:
          - 33110
          - 34011
          - 34101
          - 34110
          - 35011
          - 35101
          - 35110
          - 36011
          - 36101
          - 36110
          - 10
        exit: 0
    numero_16:
      - run: python3 numeros_introescos.py
        stdin:
          - 10000
          - 10001
        stdout:
          - 0
        exit: 0
    numero_17:
      - run: python3 numeros_introescos.py
        stdin:
          - 100
          - 300
        stdout:
          - 0
        exit: 0
    numero_18:
      - run: python3 numeros_introescos.py
        stdin:
          - 871013
          - 899999
        stdout:
          - 871013
          - 871031
          - 871103
          - 871130
          - 871301
          - 871310
          - 873011
          - 873101
          - 873110
          - 880113
          - 880131
          - 880311
          - 881013
          - 881031
          - 881103
          - 881130
          - 881301
          - 881310
          - 883011
          - 883101
          - 883110
          - 890113
          - 890131
          - 890311
          - 891013
          - 891031
          - 891103
          - 891130
          - 891301
          - 891310
          - 893011
          - 893101
          - 893110
          - 33
        exit: 0
    numero_19:
      - run: python3 numeros_introescos.py
        stdin:
          - 881310
          - 889999
        stdout:
          - 881310
          - 883011
          - 883101
          - 883110
          - 4
        exit: 0
    numero_20:
      - run: python3 numeros_introescos.py
        stdin:
          - 1234
          - 1999
        stdout:
          - 1301
          - 1310
          - 2
        exit: 0
    numero_21:
      - run: python3 numeros_introescos.py
        stdin:
          - 1235
          - 2000
        stdout:
          - 1301
          - 1310
          - 2
        exit: 0
    numero_22:
      - run: python3 numeros_introescos.py
        stdin:
          - 11031103
          - 11031130
        stdout:
          - 11031103
          - 11031104
          - 11031105
          - 11031106
          - 11031107
          - 11031108
          - 11031109
          - 11031110
          - 11031111
          - 11031112
          - 11031113
          - 11031114
          - 11031115
          - 11031116
          - 11031117
          - 11031118
          - 11031119
          - 11031120
          - 11031121
          - 11031122
          - 11031123
          - 11031124
          - 11031125
          - 11031126
          - 11031127
          - 11031128
          - 11031129
          - 11031130
          - 28
        exit: 0
    numero_23:
      - run: python3 numeros_introescos.py
        stdin:
          - 11031119
          - 11031122
        stdout:
          - 11031119
          - 11031120
          - 11031121
          - 11031122
          - 4
        exit: 0
    numero_24:
      - run: python3 numeros_introescos.py
        stdin:
          - 1
          - 1015
        stdout:
          - 1013
          - 1
        exit: 0
    numero_25:
      - run: python3 numeros_introescos.py
        stdin:
          - 2
          - 1234
        stdout:
          - 1013
          - 1031
          - 1103
          - 1130
          - 4
        exit: 0
    numero_26:
      - run: python3 numeros_introescos.py
        stdin:
          - 1111
          - 1111
        stdout:
          - 0
        exit: 0
    numero_27:
      - run: python3 numeros_introescos.py
        stdin:
          - 9999
          - 9999
        stdout:
          - 0
        exit: 0
    numero_28:
      - run: python3 numeros_introescos.py
        stdin:
          - 1000
          - 10000
        stdout:
          - 1013
          - 1031
          - 1103
          - 1130
          - 1301
          - 1310
          - 3011
          - 3101
          - 3110
          - 9
        exit: 0
    numero_29:
      - run: python3 numeros_introescos.py
        stdin:
          - 1000
          - 25000
        stdout:
          - 1013
          - 1031
          - 1103
          - 1130
          - 1301
          - 1310
          - 3011
          - 3101
          - 3110
          - 10013
          - 10031
          - 10103
          - 10113
          - 10123
          - 10130
          - 10131
          - 10132
          - 10133
          - 10134
          - 10135
          - 10136
          - 10137
          - 10138
          - 10139
          - 10143
          - 10153
          - 10163
          - 10173
          - 10183
          - 10193
          - 10213
          - 10231
          - 10301
          - 10310
          - 10311
          - 10312
          - 10313
          - 10314
          - 10315
          - 10316
          - 10317
          - 10318
          - 10319
          - 10321
          - 10331
          - 10341
          - 10351
          - 10361
          - 10371
          - 10381
          - 10391
          - 10413
          - 10431
          - 10513
          - 10531
          - 10613
          - 10631
          - 10713
          - 10731
          - 10813
          - 10831
          - 10913
          - 10931
          - 11003
          - 11013
          - 11023
          - 11030
          - 11031
          - 11032
          - 11033
          - 11034
          - 11035
          - 11036
          - 11037
          - 11038
          - 11039
          - 11043
          - 11053
          - 11063
          - 11073
          - 11083
          - 11093
          - 11103
          - 11130
          - 11203
          - 11230
          - 11300
          - 11301
          - 11302
          - 11303
          - 11304
          - 11305
          - 11306
          - 11307
          - 11308
          - 11309
          - 11310
          - 11320
          - 11330
          - 11340
          - 11350
          - 11360
          - 11370
          - 11380
          - 11390
          - 11403
          - 11430
          - 11503
          - 11530
          - 11603
          - 11630
          - 11703
          - 11730
          - 11803
          - 11830
          - 11903
          - 11930
          - 12013
          - 12031
          - 12103
          - 12130
          - 12301
          - 12310
          - 13001
          - 13010
          - 13011
          - 13012
          - 13013
          - 13014
          - 13015
          - 13016
          - 13017
          - 13018
          - 13019
          - 13021
          - 13031
          - 13041
          - 13051
          - 13061
          - 13071
          - 13081
          - 13091
          - 13100
          - 13101
          - 13102
          - 13103
          - 13104
          - 13105
          - 13106
          - 13107
          - 13108
          - 13109
          - 13110
          - 13120
          - 13130
          - 13140
          - 13150
          - 13160
          - 13170
          - 13180
          - 13190
          - 13201
          - 13210
          - 13301
          - 13310
          - 13401
          - 13410
          - 13501
          - 13510
          - 13601
          - 13610
          - 13701
          - 13710
          - 13801
          - 13810
          - 13901
          - 13910
          - 14013
          - 14031
          - 14103
          - 14130
          - 14301
          - 14310
          - 15013
          - 15031
          - 15103
          - 15130
          - 15301
          - 15310
          - 16013
          - 16031
          - 16103
          - 16130
          - 16301
          - 16310
          - 17013
          - 17031
          - 17103
          - 17130
          - 17301
          - 17310
          - 18013
          - 18031
          - 18103
          - 18130
          - 18301
          - 18310
          - 19013
          - 19031
          - 19103
          - 19130
          - 19301
          - 19310
          - 20113
          - 20131
          - 20311
          - 21013
          - 21031
          - 21103
          - 21130
          - 21301
          - 21310
          - 23011
          - 23101
          - 23110
          - 225
submit50:
  files: *check50_files
